### ISSUE TITLE
Random disconnection on admin dashboard

### ISSUE THREAD

**Issue by 5ika** [jelastic-jps/wordpress-cluster#2]
Hi,
I've some headache trying to fix a strange bug: I have installed an existent Wordpress in a cluster env (from the marketplace) on hidora.com. But when I log in on the admin dashboard (/wp-admin), I am randomly disconnected and redirected to the login page, saying that my session has expired. The disconnection happened in ~10-15s when I try to acces to an admin page or I stay a few moment without activity.

This not happened with the same installation of Wordpress in a simple env with one app server and no load balancer.

This is what I tried:
- Check if sticky session works with load balancers : one user is always redirected to the same app serveur instance
- Update timezone on app servers & load balancers
- Check timezone and cookie expiration (I'm in timezone GMT+1, Switzerland)
- Check every URL in WP settings
- Disable all extensions
- Clear cache and cookies in the browser

But nothing help. An idea of the problem ?

**Comment by mrAlexZT** [comment]
I've installed Wordpress Cluster from the Marketplace.
- Login into WP Admin Panel ("Remember Me" option also checked) using credentials from email
- Wait 1 hour
- Click several links inside AP
All work fine for me. No logout from AP.

**Comment by siruslan** [comment]
@5ika what url do you use for login? can you print the full url here?

**Comment by 5ika** [comment]
Full URL is http://swiss-blackfriday.hidora.com/wp-admin
I need to add that it's a WP multisite (required by client).

**Comment by siruslan** [comment]
@5ika the url looks right... hm.. could you install another cluster from the same package and check if you can reproduce the issue at a new one?

**Comment by 5ika** [comment]
@siruslan I've finally found the problem: the cluster of mysql servers not works as wanted and requests are randomly sent to one or the other server. But the mysql servers are not correctly synchronized and the responses are different.
In a quick fix, I've removed the second db server and it worked but I'm not an expert in mysql for a real solution.

**Comment by siruslan** [comment]
@5ika that is strange, than you for the report. @sych74 will take a look at the db cluster setup automation early next week.
