### ISSUE TITLE
Nginx configuration not copied on horizontal scale

### ISSUE THREAD

**Issue by 5ika** [jelastic-jps/wordpress-cluster#4]
Hi,
I'm using a Wordpress cluster env with a WP in multi-site mode.
For the multi-site to work, I modified the configuration of nginx on the App servers.
But when a new app server is added, it doesn't take the custom configuration of nginx, resulting to 404 errors at the worst moments.
Is there a way to copy the nginx config on the new app server ? Using an add-on manifest ?

**Comment by sych74** [comment]
Hello,
You can move custom configuration to the storage or master node of nginxphp layer and mount it to the all nodes. During the further scaling this configuration will be mounted to the new node. Moreover, this will make configuration changing easier.

**Comment by 5ika** [comment]
Thanks a lot !
It's seems obvious now --'
